@startuml "erd"

entity "Навыки" as skills
{
    ID_Навык : int <<PK>>
    Название : nvarchar(20)
}

entity "Каталог навыков специалиста" as skills_cat
{
    ID_Кат_нав : int <<PK>>
    ID_Навыка : int <<FK>>
    ID_Специалиста : int <<FK>>
}

entity "Специализации" as spec_enum
{
    ID_Специализация : int <<PK>>
    Название : nvarchar(30)
}

entity "Каталог специализаций специалиста" as spec_cat
{
    ID_Кат_специализаций_специалистов : int <<PK>>
    ID_Специализации : int <<FK>>
    ID_Специалиста : int <<FK>>
}

entity "Страна" as countries 
{
    ID_Страна : int <<PK>>
    Название : nvarchar(50)
}

entity "Город" as cities 
{
    ID_Город : int <<PK>>
    ID_Страна : int <<FK>>
    Название : nvarchar(50)
}

entity "Пользователь" as users 
{
    * ID_Пользователь : int <<PK>>
    * ID_Страна : int <<FK>>
    * ID_Город : int <<FK>>
    * email : nvarchar(30)
    * Пароль : nvarchar(30)
    * Имя : nvarchar(20)
    * Фамилия : nvarchar(20)
    * Отчество : nvarchar(20)
    * Дата рождения : datetime 
    * О себе : nvarchar(250)
    Портфорлио : nvarchar(400)
    ID_Роль : int
}

enum "Заявка" as request 
{
    * ID_Заявка : int <<PK>>
    * ID_Заказчик : int <<FK>>
    * ID_Специалист : int <<FK>>
    Время связи : datatime 
    Статус_заявки : int
    ID_Платформа : int
    Оценка_заказчика : int 
    Комментарий_заказчика : nvarchar(250)
    Оценка_специалиста : int 
    Комментарий_специалиста : nvarchar(250)
}

users ||--o{ request : может создать

skills_cat }o--|| users : имеет
skills_cat }o--|| skills

spec_cat }o--|| users : имеет
spec_cat }o--|| spec_enum

users }o--|| cities
countries ||--|{ cities

'request ||--|| appl 


@enduml